trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Build Maven Project
- task: Maven@4
  displayName: 'Build Maven Project'
  inputs:
    mavenPomFile: 'ravi/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'

# Copy entire project (including pom.xml)
- task: CopyFiles@2
  displayName: 'Copy Project Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish artifact for Release Pipeline
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'